# @format

name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Setup .NET SDK (for Blazor app)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # Make sure this version matches your project

      # Step 3: Clean and Restore before building
      - name: Clean and Restore
        run: |
          dotnet clean SilentEar/SilentEar.csproj
          dotnet restore SilentEar/SilentEar.csproj

      # Step 4: Publish the Blazor Project with clean build
      - name: Publish .NET Project
        run: dotnet publish SilentEar/SilentEar.csproj -c Release -o release --nologo --force

      # Step 5: Add .nojekyll file to prevent Jekyll processing
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # Step 6: Fix missing CSS file (create empty one if it doesn't exist)
      - name: Create missing CSS file if needed
        run: |
          if [ ! -f "release/wwwroot/SilentEar.styles.css" ]; then
            echo "/* Generated styles */" > release/wwwroot/SilentEar.styles.css
          fi

      # Step 7: Modify base tag for GitHub Pages subdirectory deployment
      - name: Change base tag in index.html
        run: sed -i 's|<base href="/SilentEar/" />|<base href="/SilentEar/" />|g' release/wwwroot/index.html

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Target the gh-pages branch
          folder: release/wwwroot # Path to the built app
